on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version: [26.3, 27.2, 28.2, snapshot]
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
        if: ${{ matrix.os != 'windows-latest' }}
      - uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs-version }}
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          conda install -c conda-forge pandoc
          conda install -c anaconda jupyter
          curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/eldev | sh

          # Make eldev available to all future actions
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Check Jupyter version
        run: |
          mkdir -p $(jupyter --runtime-dir)
          jupyter --paths
          jupyter --version
          jupyter kernelspec list
      - name: Byte compilation
        run: |
          make compile
      - name: Run tests
        run: |
          make test
